# generated-from:2b032db735b20164e9573e897cc0e43f41777de7e64c1a204fe2943d0d98999e DO NOT REMOVE, DO UPDATE

name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Go Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: stable
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install make (Windows)
      if: runner.os == 'Windows'
      run: choco install -y make mingw

    - name: Install
      run: make install

    - name: Check
      run: make check
      env:
        GOLANGCI_LINTERS: gosec

    - name: Docker Build
      if: runner.os == 'Linux'
      run: make dev-docker

    - name: Docker Push
      if: runner.os == 'Linux'
      run: |+
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          make dev-push
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
